name: Docker-CI

on:
  push:
    branches:
      - docker
  pull_request:
    types: [opened, edited]

jobs:
  build-frontend-app:
    if: ${{ github.base_ref == 'docker' || github.ref == 'refs/heads/docker' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@fd7ecdac7caf8e2c541a48c9bcc280aae59a8461 # master

      - name: Cache Docker layers
        uses: jpribyl/action-docker-layer-caching@616dc4b3a7ba46d074f885cc681ca9db6309f376 # master
        continue-on-error: true
        # workaround for https://github.com/satackey/action-docker-layer-caching/issues/169#issuecomment-1217408538
        with:
          key: docker-layer-cache-{hash}
          restore-keys: |
            docker-layer-cache-
            layer-docker-layer-cache-

      - name: Build the app
        working-directory: frontend/scripts/docker-buildfiles
        run: docker-compose build --progress=plain
